<?php
namespace app\index\controller;


use app\common\model\Dfile;
use think\Controller;
use think\Request;

class BaseController extends Controller {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    protected function https_request($url) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        $out = curl_exec($ch);
        curl_close($ch);
        return json_decode($out, true);
    }

    protected function https_post($url,$Data) {

           // $url = 'https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token=' . $Token;
            //初始化
            $ch = curl_init();
            //设置参数
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $Data);
            curl_setopt($ch, CURLOPT_HEADER, 0);
            //采集
            $output = curl_exec($ch);
            if (curl_errno($ch)) {
                dump(curl_error($ch));
            }
            //关闭
            curl_close($ch);
            $res = json_decode($output);
            return $res;

    }

}
