<?php
namespace app\index\controller;


use app\common\model\Dfile;
use think\Controller;
use think\Request;

class BaseController extends Controller {

  public function _initialize() {
      parent::_initialize(); // TODO: Change the autogenerated stub

  }
}
